version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: packages/frontend/dev.Dockerfile
    image: template-project-frontend:latest-dev
    ports:
      - ${FRONTEND_PORT}:3000
      - 1234:1234
    volumes:
      - /usr/src/app/packages/frontend/node_modules
      - ./packages/frontend:/usr/src/app/packages/frontend
      - /usr/src/app/packages/backend/node_modules
      - ./packages/backend:/usr/src/app/packages/backend

  backend:
    build:
      context: .
      dockerfile: packages/backend/dev.Dockerfile
    image: template-project-backend:latest-dev
    ports:
      - ${BACKEND_PORT}:3000
    volumes:
      - /usr/src/app/packages/backend/node_modules
      - ./packages/backend:/usr/src/app/packages/backend

  postgres:
    image: postgres:12
    environment:
      POSTGRES_DB: ${PG_DATABASE}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_USER: ${PG_USERNAME}
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - ${PGADMIN_PORT}:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    volumes:
      - pgadmindata:/usr/lib/pgadmin

  redis:
    image: redis
    command:
      - redis-server
      - --requirepass ${REDIS_PASSWORD}
    volumes:
      - redisdata:/var/lib/redis

volumes:
  pgdata:
  pgadmindata:
  redisdata:
