version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: packages/frontend/Dockerfile
    image: template-project-frontend:latest
    ports:
      - ${FRONTEND_PORT}:80

  backend:
    build:
      context: .
      dockerfile: packages/backend/Dockerfile
    image: template-project-backend:latest
    ports:
      - ${BACKEND_PORT}:3000

  postgres:
    image: postgres:12
    environment:
      POSTGRES_DB: ${PG_DATABASE}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_USER: ${PG_USERNAME}
    volumes:
      - ${PG_DATA_FOLDER}:/var/lib/postgresql/data

  redis:
    image: redis
    command:
      - redis-server
      - --requirepass ${REDIS_PASSWORD}
    volumes:
      - ${REDIS_DATA_FOLDER}:/var/lib/redis
